# PostgreSQL version 3.x
#   gem install pg
#
#   Ensure the PostgreSQL gem is defined in your Gemfile
#   gem 'pg'
#
development:
  adapter: postgresql
  encoding: utf8
  database: chores_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf8
  database: chores_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: chores_production
  pool: 5
  timeout: 5000
