# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc02a4955892196859253e7a2c8170e79cd6a74e5a33a759f4ace9958c44cf8ce02a3a56aacb63cf6710e9566508424638c771f54af6aa5053713c327cc92f89

test:
  secret_key_base: a52a9481cf38166456560a0683615a028fdba3089e290194c48207cb8a7a3eba6beb47aa1bd48aba631dc244712e20ca1bfdb2d35b2c44436a559ec63a5cf3cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
